version = 1

exclude_patterns = [
  "config/**",
  "tests/**"
]

test_patterns = [
    "tests/**"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "requirements/prod.txt",
  "requirements/test.txt"
]
  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 88


[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["Dockerfile"]
