[tool.black]
verbose = true
target-version = ["py39"]

[tool.isort]
atomic = true
color_output = true
verbose = true
only_modified = true
ensure_newline_before_comments = true
force_single_line = true
include_trailing_comma = true
use_parentheses = true
force_grid_wrap = 0
lines_after_imports = 2
lines_between_types = 1
line_length = 88
multi_line_output = 3
py_version = 39
